apiVersion: v1
kind: Service
metadata:
  name: application-backend
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30083  # You can specify a port or let Kubernetes choose one
  selector:
    app: application-backend
